### ISSUE TITLE
Hatalı link

### ISSUE THREAD

**Issue by gokaygurcan** [ilkgunel/ilkgunel.github.io#1]
Merhaba,
turkcekaynaklar.com'a yaptığınız katkı sayesinde sitenize ulaştım. Sağ üstte bulunan GitHub link'i hatalı görünüyor:
https://github.com/ilkgunel/ilkgunel.github.io/blob/master/index.html#L97

İyi çalışmalar,
G.

**Comment by ilkgunel** [comment]
Merhaba,
Bilgilendirme için teşekkür ederim. İlgili sorunu giderdim.
